export type IndustrySlug =
  | "restaurant" | "cafe" | "bar" | "bakery" | "food-truck" | "kiosk"
  | "retail" | "hair-salon" | "beauty-salon" | "service-business";

export interface IndustryContent {
  slug: IndustrySlug;
  eyebrow: { en: string; de: string };
  title: { en: string; de: string };
  lede: { en: string; de: string };
  metaTitle: { en: string; de: string };
  metaDescription: { en: string; de: string };
  painPoints: { en: string[]; de: string[] };
  features: { en: string[]; de: string[] };
  proof: { en: string; de: string };
}

const make = (
  slug: IndustrySlug,
  enTitle: string, deTitle: string,
  enLede: string, deLede: string,
  enMeta: string, deMeta: string,
  enMetaD: string, deMetaD: string,
  pains: { en: string[]; de: string[] },
  feats: { en: string[]; de: string[] },
  proof: { en: string; de: string },
): IndustryContent => ({
  slug,
  eyebrow: { en: enTitle.split(" POS")[0] + " POS", de: deTitle.split(" für")[0] },
  title: { en: enTitle, de: deTitle },
  lede: { en: enLede, de: deLede },
  metaTitle: { en: enMeta, de: deMeta },
  metaDescription: { en: enMetaD, de: deMetaD },
  painPoints: pains,
  features: feats,
  proof,
});

export const industries: Record<IndustrySlug, IndustryContent> = {
  restaurant: make("restaurant",
    "The POS system restaurants actually want.",
    "Das Kassensystem, das Restaurants wirklich wollen.",
    "Course-by-course KDS, handheld waiter ordering, split bills, table maps and TSE compliance — purpose-built for full-service restaurants.",
    "Gang-für-Gang-KDS, mobile Kellner-Bestellung, geteilte Rechnungen, Tischpläne und TSE-Konformität — speziell für die Vollservice-Gastronomie.",
    "Restaurant POS System — TSE-ready, KDS included | GastroPos",
    "Kassensystem für Restaurants — TSE-konform, KDS inklusive | GastroPos",
    "Full-service restaurant POS with kitchen display, waiter app, table management, course timing and TSE compliance. Live in 2 hours.",
    "Vollservice-Restaurantkasse mit Küchenmonitor, Kellner-App, Tischverwaltung, Gangsteuerung und TSE-Konformität. In 2 Stunden einsatzbereit.",
    { en: ["Waiters lose minutes walking between tables and the POS", "Kitchen tickets get lost or misread", "Splitting a bill 6 ways takes 10 minutes", "End-of-night cash never matches the report"],
      de: ["Service-Team verliert Zeit zwischen Tisch und Kasse", "Küchenbons gehen verloren oder werden falsch gelesen", "Eine Rechnung auf 6 Gäste teilen dauert 10 Minuten", "Bargeld am Abend stimmt nie mit dem Bericht überein"] },
    { en: ["Table map with status, server and timer", "Handheld waiter ordering with course timing", "KDS with station routing", "Split bills by item, seat or share", "Tip pooling and distribution", "TSE + DATEV included"],
      de: ["Tischplan mit Status, Service und Timer", "Mobile Kellner-App mit Gangsteuerung", "KDS mit Stations-Routing", "Rechnungen pro Artikel, Sitz oder Anteil splitten", "Trinkgeldpool und -verteilung", "TSE + DATEV inklusive"] },
    { en: "“GastroPos has increased our efficiency and confidence in serving many customers at once. The KDS just works great.” — Kevin Gasiewski, Hechtseeterrassen",
      de: '„GastroPos hat unsere Effizienz und unser Vertrauen beim Bedienen vieler Gäste enorm gesteigert. Das KDS funktioniert einfach großartig.“ — Kevin Gasiewski, Hechtseeterrassen' }),
  cafe: make("cafe",
    "Café POS that keeps the line moving.",
    "Café-Kasse, die die Schlange in Bewegung hält.",
    "Fast item entry, modifier-heavy menus, loyalty stamps and grab-and-go ordering — built for cafés, coffee shops and quick-service bakeries.",
    "Schnelle Artikelerfassung, modifier-lastige Karten, Treuestempel und Grab-and-Go — gebaut für Cafés, Kaffeehäuser und Bäckereien.",
    "Café POS System with Loyalty | GastroPos",
    "Café-Kassensystem mit Treueprogramm | GastroPos",
    "Café POS with one-tap entry, drink modifiers, loyalty stamps and grab-and-go ordering. TSE-ready, KDS included.",
    "Café-Kasse mit Ein-Klick-Erfassung, Getränke-Modifiern, Treuestempeln und Grab-and-Go-Bestellung. TSE-konform, KDS inklusive.",
    { en: ["Morning rush takes too long per order", "Modifiers (oat, decaf, double shot) slow down the line", "No loyalty = no reason to come back"],
      de: ["Morgendlicher Rush dauert zu lange pro Bestellung", "Modifier (Hafer, entkoffeiniert, doppelter Shot) bremsen die Linie", "Keine Treue = kein Grund zurückzukommen"] },
    { en: ["One-tap drink builder with modifiers", "Loyalty stamps and rewards built-in", "Customer display for tip prompts", "QR pre-ordering from the table", "Pastry counter and weight-based items", "TSE + DSFinV-K + DATEV"],
      de: ["Ein-Tipp-Getränkebuilder mit Modifiern", "Treuestempel und Rewards integriert", "Kundendisplay mit Trinkgeld-Prompt", "QR-Vorbestellung vom Tisch", "Gebäcktheke und gewichtsbasierte Artikel", "TSE + DSFinV-K + DATEV"] },
    { en: "“The best is the service, always available and helpful. It is really fun to work with GastroPos.” — Rolf Bickel, The Baristo",
      de: '„Das Beste ist der Service, immer erreichbar und hilfsbereit. Es macht wirklich Spaß, mit GastroPos zu arbeiten.“ — Rolf Bickel, The Baristo' }),
  bar: make("bar",
    "Bar POS that survives a Saturday night.",
    "Bar-Kasse, die einen Samstagabend übersteht.",
    "Open tabs, quick rounds, pour cost tracking and split-the-check bartending — built for cocktail bars, pubs and clubs.",
    "Offene Tabs, schnelle Runden, Pour-Cost-Tracking und einfaches Split-the-Check — gebaut für Cocktailbars, Pubs und Clubs.",
    "Bar POS System with Tabs & Pour Cost | GastroPos",
    "Bar-Kassensystem mit Tabs & Pour-Cost | GastroPos",
    "Bar POS with open tabs, pre-authorization, pour cost tracking and lightning-fast round entry. TSE-compliant.",
    "Bar-Kasse mit offenen Tabs, Vorautorisierung, Pour-Cost-Tracking und blitzschneller Rundenerfassung. TSE-konform.",
    { en: ["Tabs get lost or merged wrong", "Free pours destroy margin", "Cash & card never reconcile"],
      de: ["Tabs gehen verloren oder werden falsch zusammengeführt", "Freie Pours zerstören die Marge", "Bar- und Kartenzahlung stimmen nie überein"] },
    { en: ["Open tabs with card pre-auth", "Pour cost reports per drink and bartender", "Happy-hour pricing schedules", "Round entry with quick-keys", "Speed-rail layout designer"],
      de: ["Offene Tabs mit Karten-Vorautorisierung", "Pour-Cost-Berichte pro Drink und Bartender", "Happy-Hour-Preispläne", "Rundenerfassung mit Quick-Keys", "Speed-Rail-Layout-Designer"] },
    { en: "Bars on GastroPos close 18% faster at end-of-night.", de: "Bars mit GastroPos schließen am Abend 18 % schneller ab." }),
  bakery: make("bakery",
    "Bakery POS with weight-based items and pre-orders.",
    "Bäckerei-Kasse mit Gewichtsartikeln und Vorbestellungen.",
    "Scale integration, batch baking schedules, B2B wholesale orders and online pre-ordering for cakes and bread.",
    "Waagen-Integration, Backpläne, B2B-Großhandelsbestellungen und Online-Vorbestellung für Torten und Brot.",
    "Bakery POS System with Pre-Orders | GastroPos",
    "Bäckerei-Kassensystem mit Vorbestellungen | GastroPos",
    "POS for bakeries with scale integration, batch baking, B2B wholesale, cake pre-orders and TSE compliance.",
    "Kasse für Bäckereien mit Waagen-Integration, Backplänen, B2B-Großhandel, Torten-Vorbestellung und TSE-Konformität.",
    { en: ["Counter staff weighs and rings up manually", "Cake pre-orders live on paper or WhatsApp", "Wholesale invoices done in Excel"],
      de: ["Personal wiegt und kassiert manuell", "Torten-Vorbestellungen auf Papier oder WhatsApp", "Großhandelsrechnungen in Excel"] },
    { en: ["Integrated scale (€/kg auto-calc)", "Online cake & bread pre-ordering", "Wholesale customer pricing", "Batch baking schedule view", "Daily waste tracking"],
      de: ["Integrierte Waage (€/kg Auto-Berechnung)", "Online-Vorbestellung für Torten & Brot", "Großhandelspreise pro Kunde", "Backplan-Ansicht", "Tägliche Schwund-Erfassung"] },
    { en: "Bakeries cut wholesale invoice time by 80%.", de: "Bäckereien sparen 80 % Zeit bei Großhandelsrechnungen." }),
  "food-truck": make("food-truck",
    "Food truck POS that works on 3G.",
    "Foodtruck-Kasse, die auch im 3G-Netz läuft.",
    "Offline-first, mobile printer support, single-tap setup and contactless payments — built for trucks, market stalls and pop-ups.",
    "Offline-fähig, mobiler Druckersupport, Ein-Klick-Setup und kontaktloses Bezahlen — gebaut für Foodtrucks, Marktstände und Pop-ups.",
    "Food Truck POS System — Offline & Mobile | GastroPos",
    "Foodtruck-Kassensystem — Offline & Mobil | GastroPos",
    "Offline-first POS for food trucks, market stalls and pop-ups. Mobile printer, contactless payments, TSE-ready.",
    "Offline-fähige Kasse für Foodtrucks, Marktstände und Pop-ups. Mobiler Drucker, kontaktlose Zahlung, TSE-konform.",
    { en: ["Spotty 3G drops the POS mid-order", "Hardware is bulky and breaks", "Cash management on the road is a nightmare"],
      de: ["3G bricht mitten in der Bestellung ab", "Hardware ist sperrig und geht kaputt", "Bargeldverwaltung unterwegs ist ein Albtraum"] },
    { en: ["100% offline-first — syncs when back online", "Phone-as-POS mode", "Mobile Bluetooth printer support", "Apple Pay, Google Pay, SumUp, Stripe Tap to Pay"],
      de: ["100 % offline-first — synchronisiert bei Verbindung", "Phone-as-POS-Modus", "Mobiler Bluetooth-Druckersupport", "Apple Pay, Google Pay, SumUp, Stripe Tap to Pay"] },
    { en: "Operators run multiple trucks from one dashboard.", de: "Betreiber steuern mehrere Trucks aus einem Dashboard." }),
  kiosk: make("kiosk",
    "Kiosk & self-order terminal POS.",
    "Kiosk- & Self-Order-Terminal-Kasse.",
    "Turn any tablet into a self-ordering kiosk that takes orders, payments and prints to the kitchen — no cashier required.",
    "Verwandeln Sie jedes Tablet in einen Self-Order-Kiosk, der Bestellungen aufnimmt, kassiert und in die Küche druckt — ohne Personal.",
    "Self-Order Kiosk POS System | GastroPos",
    "Self-Order-Kiosk-Kassensystem | GastroPos",
    "Self-ordering kiosk for QSR, ghost kitchens and snack bars. Upsells, allergens, multilingual and contactless payment.",
    "Self-Order-Kiosk für QSR, Ghost-Kitchens und Imbiss. Upsells, Allergene, mehrsprachig und kontaktlos.",
    { en: ["Counter staff is the bottleneck during rush", "Customers want to browse — not be rushed", "Upsells get forgotten"],
      de: ["Personal an der Theke ist der Flaschenhals", "Kunden wollen stöbern — nicht gehetzt werden", "Upsells werden vergessen"] },
    { en: ["Kiosk mode (fullscreen, no app exit)", "Automatic upsells per item", "Multilingual menu (DE/EN/TR/AR/…)", "Allergen and nutrition badges", "Contactless and Apple Pay only mode"],
      de: ["Kiosk-Modus (Vollbild, kein App-Exit)", "Automatische Upsells pro Artikel", "Mehrsprachige Karte (DE/EN/TR/AR/…)", "Allergen- und Nährwert-Badges", "Nur kontaktlos & Apple Pay Modus"] },
    { en: "Kiosk-equipped QSRs see +22% average ticket.", de: "QSR mit Kiosk sehen +22 % durchschnittlichen Bonwert." }),
  retail: make("retail",
    "Retail POS for boutiques, concept stores and shops.",
    "Einzelhandels-Kasse für Boutiquen, Concept Stores und Shops.",
    "Barcode scanning, size/color variants, stocktake on iPad, customer accounts and Shopify sync — built for modern retail.",
    "Barcode-Scan, Größen-/Farb-Varianten, iPad-Inventur, Kundenkonten und Shopify-Sync — gebaut für modernen Handel.",
    "Retail POS System for Boutiques & Shops | GastroPos",
    "Einzelhandels-Kassensystem für Boutiquen & Shops | GastroPos",
    "Retail POS with barcodes, variants, stocktake, Shopify sync, customer accounts and TSE compliance. Built for boutiques and concept stores.",
    "Einzelhandels-Kasse mit Barcodes, Varianten, Inventur, Shopify-Sync, Kundenkonten und TSE-Konformität. Für Boutiquen und Concept Stores.",
    { en: ["Stock counts never match", "Online and in-store inventory drift apart", "Customer history lives nowhere"],
      de: ["Bestände stimmen nie überein", "Online- und In-Store-Bestände driften auseinander", "Kundenhistorie existiert nirgends"] },
    { en: ["Barcode scanning + label printing", "Size and color variants", "Live two-way Shopify sync", "iPad stocktake", "Customer accounts and store credit", "Layaway and back-orders"],
      de: ["Barcode-Scan + Etikettendruck", "Größen- und Farb-Varianten", "Live-Shopify-Sync", "iPad-Inventur", "Kundenkonten und Guthaben", "Anzahlung und Nachbestellung"] },
    { en: "Retailers cut stock variance from 8% to under 2%.", de: "Händler senken Bestandsabweichung von 8 % auf unter 2 %." }),
  "hair-salon": make("hair-salon",
    "Hair salon POS with online booking.",
    "Friseur-Kasse mit Online-Buchung.",
    "Appointments, stylist commissions, service + retail in one ticket, customer history and SMS reminders.",
    "Termine, Stylisten-Provisionen, Service + Retail in einem Bon, Kundenhistorie und SMS-Erinnerungen.",
    "Hair Salon POS & Booking System | GastroPos",
    "Friseur-Kassensystem & Buchung | GastroPos",
    "POS and online booking for hair salons. Stylist commissions, customer history, SMS reminders and TSE compliance.",
    "Kasse und Online-Buchung für Friseure. Stylisten-Provisionen, Kundenhistorie, SMS-Erinnerungen und TSE-Konformität.",
    { en: ["No-shows cost real money", "Commissions calculated by hand", "Service + retail mixed badly on tickets"],
      de: ["No-Shows kosten echtes Geld", "Provisionen werden von Hand berechnet", "Service + Retail auf Bons schlecht getrennt"] },
    { en: ["Public booking page under your domain", "SMS + email appointment reminders", "Stylist commission per service/product", "Color formula history per customer", "Tip distribution by stylist"],
      de: ["Öffentliche Buchungsseite unter eigener Domain", "SMS- + E-Mail-Erinnerungen", "Stylisten-Provision pro Service/Produkt", "Color-Formel-Historie pro Kunde", "Trinkgeldverteilung pro Stylist"] },
    { en: "Salons reduce no-shows by 35% with SMS reminders.", de: "Salons reduzieren No-Shows um 35 % durch SMS-Erinnerungen." }),
  "beauty-salon": make("beauty-salon",
    "Beauty salon & spa POS.",
    "Beauty-Salon- & Spa-Kasse.",
    "Multi-room scheduling, package & series tracking, gift vouchers and product sales — all in one calendar.",
    "Mehrraum-Planung, Pakete & Serien, Gutscheine und Produktverkauf — alles in einem Kalender.",
    "Beauty Salon & Spa POS Software | GastroPos",
    "Beauty-Salon & Spa-Kassensoftware | GastroPos",
    "POS and booking for beauty salons and spas. Multi-room calendar, packages, gift cards and product retail.",
    "Kasse und Buchung für Beauty-Salons und Spas. Mehrraum-Kalender, Pakete, Gutscheine und Produktverkauf.",
    { en: ["Multiple rooms = overlapping bookings", "Package series tracked on Post-its", "Gift cards leak revenue"],
      de: ["Mehrere Räume = überlappende Buchungen", "Paket-Serien auf Post-its", "Gutscheine verlieren Umsatz"] },
    { en: ["Multi-room/resource scheduling", "Series and package balance tracking", "Gift voucher issuance and redemption", "Therapist commission and tips", "Consent forms per treatment"],
      de: ["Mehrraum-/Ressourcenplanung", "Serien- und Paket-Restguthaben", "Gutschein-Ausgabe und -Einlösung", "Therapeuten-Provision und Trinkgeld", "Einwilligungsformulare pro Behandlung"] },
    { en: "Spas turn series-pack customers into repeat regulars.", de: "Spas machen aus Serien-Kunden treue Stammgäste." }),
  "service-business": make("service-business",
    "POS for service businesses.",
    "Kasse für Dienstleister.",
    "Appointments, deposits, recurring services, mobile invoicing and customer history — for tattoo studios, repair shops, dog groomers and more.",
    "Termine, Anzahlungen, wiederkehrende Services, mobile Rechnungen und Kundenhistorie — für Tattoo-Studios, Reparatur, Hundesalons und mehr.",
    "POS for Service Businesses | GastroPos",
    "Kasse für Dienstleister | GastroPos",
    "Flexible POS for service businesses: appointments, deposits, recurring services, mobile invoicing and customer history.",
    "Flexible Kasse für Dienstleister: Termine, Anzahlungen, wiederkehrende Services, mobile Rechnungen und Kundenhistorie.",
    { en: ["Deposits chased manually", "Recurring jobs forgotten", "Invoicing happens at 11pm"],
      de: ["Anzahlungen werden manuell verfolgt", "Wiederkehrende Aufträge vergessen", "Rechnungen werden um 23 Uhr geschrieben"] },
    { en: ["Online booking with deposit at checkout", "Recurring service automation", "Mobile invoicing & e-receipts", "Customer photo and notes history"],
      de: ["Online-Buchung mit Anzahlung", "Automatisierung wiederkehrender Services", "Mobile Rechnungen & E-Belege", "Kundenfoto- und Notiz-Historie"] },
    { en: "Service operators save 6+ hours of admin per week.", de: "Dienstleister sparen 6+ Stunden Verwaltung pro Woche." }),
};
