/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/signin': typeof SigninRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/signin': typeof SigninRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/signin': typeof SigninRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate'
    | '/compare'
    | '/contact'
    | '/demo'
    | '/partners'
    | '/pricing'
    | '/signin'
    | '/industries/$slug'
    | '/legal/$slug'
    | '/product/$slug'
    | '/resources/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate'
    | '/compare'
    | '/contact'
    | '/demo'
    | '/partners'
    | '/pricing'
    | '/signin'
    | '/industries/$slug'
    | '/legal/$slug'
    | '/product/$slug'
    | '/resources/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliate'
    | '/compare'
    | '/contact'
    | '/demo'
    | '/partners'
    | '/pricing'
    | '/signin'
    | '/industries/$slug'
    | '/legal/$slug'
    | '/product/$slug'
    | '/resources/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliateRoute: typeof AffiliateRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  PartnersRoute: typeof PartnersRoute
  PricingRoute: typeof PricingRoute
  SigninRoute: typeof SigninRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliateRoute: AffiliateRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  PartnersRoute: PartnersRoute,
  PricingRoute: PricingRoute,
  SigninRoute: SigninRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
